### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined 

### ISSUE THREAD

**Issue by Garib-ka-code** [alirezamirian/angular-material-swipe-to-refresh#9]

**Comment by alirezamirian** [comment]
Can you provide more information? line and column for example. 
Demo works without error with the latest version.

**Comment by vishalrajole** [comment]
@Garib-ka-code @alirezamirian `event.touches[0].pageY`
should be `event.originalEvent.touches[0].pageY`

reference: https://stackoverflow.com/questions/7965538/js-how-does-event-touches-property-work

**Comment by chm0815** [comment]
same problem here.
